# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$os$username$hostname$directory$git_branch$git_status
$status$character'''

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[username]
show_always = true

[hostname]
ssh_only = true
format = "[ssh:$hostname](bold red) "

[os]
disabled = false

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = "[$all_status$ahead_behind]($style) "

[status]
disabled = false
format = "[exit:$status](bold red) "

[character]
success_symbol = "[❯](bold blue) "
error_symbol = "[❯](bold red) "
