# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[┌───────────────────>](bold blue)
[│](bold blue)$os$username$hostname$directory$rust$nodejs$deno$time
[└─>](bold blue) '''

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[username]
show_always = true

[hostname]
ssh_only = true
format = "[ssh:$hostname](bold red) "

[time]
disabled = false

[os]
disabled = false
